package move;

public enum Flag {
	HAS_STATUS_CONDITION,
	HAS_ADDITIONAL_EFFECT,
	IS_HIGH_CRIT_RATIO,
	IS_CONTACT,
	IS_FIXED_DAMAGE,
	IS_OHKO,
	IS_MULTISTRIKE,
	IS_CONSECUTIVE,
	IS_DEFROST_USER,
	IS_DEFROST_TARGET;
}
